// Generated from src/ehentai. Do not edit this file directly.
// Run: node scripts/build-source.js ehentai
// Source entry for generated root ehentai.js.
// Keep runtime output standalone: no imports or exports in generated artifact.
const EhentaiModules = {
  parsers: {},
  features: {},
};

EhentaiModules.hasValue = function hasValue(value) {
  return value !== null && value !== undefined && value !== "";
};

EhentaiModules.buildQuery = function buildQuery(params) {
  return Object.entries(params)
    .filter(([, value]) => EhentaiModules.hasValue(value))
    .map(
      ([key, value]) =>
        `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`,
    )
    .join("&");
};

EhentaiModules.buildFormBody = function buildFormBody(params) {
  return Object.entries(params)
    .filter(([, value]) => value !== null && value !== undefined)
    .map(
      ([key, value]) =>
        `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`,
    )
    .join("&");
};

EhentaiModules.URL_HOSTS = {
  EH: "e-hentai.org",
  EX: "exhentai.org",
  FORUMS: "forums.e-hentai.org",
  API_EH: "api.e-hentai.org",
};

EhentaiModules.buildBaseUrl = function buildBaseUrl(domain) {
  return `https://${domain}`;
};

EhentaiModules.buildPathUrl = function buildPathUrl(baseUrl, path) {
  const normalizedPath = String(path || "").replace(/^\/+/, "");
  if (!normalizedPath) {
    return String(baseUrl);
  }
  return `${baseUrl}/${normalizedPath}`;
};

EhentaiModules.buildPathQueryUrl = function buildPathQueryUrl(
  baseUrl,
  path,
  params,
  keepTrailingQuestion = false,
) {
  const base = EhentaiModules.buildPathUrl(baseUrl, path);
  const query = EhentaiModules.buildQuery(params || {});
  if (!query) {
    return keepTrailingQuestion ? `${base}?` : base;
  }
  return `${base}?${query}`;
};

EhentaiModules.buildCdnSourceUrl = function buildCdnSourceUrl(fileName) {
  return EhentaiModules.buildPathUrl(
    "https://cdn.jsdelivr.net/gh/mythic3011/venera-configs@main",
    fileName,
  );
};

EhentaiModules.buildApiUrl = function buildApiUrl(baseUrl) {
  if (baseUrl.includes(EhentaiModules.URL_HOSTS.EX)) {
    return EhentaiModules.buildPathUrl(
      EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.EX),
      "api.php",
    );
  }
  return EhentaiModules.buildPathUrl(
    EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.API_EH),
    "api.php",
  );
};

EhentaiModules.buildEhNewsUrl = function buildEhNewsUrl() {
  return EhentaiModules.buildPathUrl(
    EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.EH),
    "news.php",
  );
};

EhentaiModules.buildForumsLoginUrl = function buildForumsLoginUrl() {
  return EhentaiModules.buildPathQueryUrl(
    EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.FORUMS),
    "index.php",
    { act: "Login", CODE: "00" },
  );
};

EhentaiModules.buildForumsHomeUrl = function buildForumsHomeUrl() {
  return `${EhentaiModules.buildPathUrl(
    EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.FORUMS),
    "",
  )}/`;
};

EhentaiModules.buildForumsIndexRefererUrl =
  function buildForumsIndexRefererUrl() {
    return EhentaiModules.buildPathQueryUrl(
      EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.FORUMS),
      "index.php",
      {},
      true,
    );
  };

EhentaiModules.buildEhCookieUrl = function buildEhCookieUrl() {
  return EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.EH);
};

EhentaiModules.buildExCookieUrl = function buildExCookieUrl() {
  return EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.EX);
};

EhentaiModules.buildForumsCookieUrl = function buildForumsCookieUrl() {
  return EhentaiModules.buildBaseUrl(EhentaiModules.URL_HOSTS.FORUMS);
};

EhentaiModules.buildPopularUrl = function buildPopularUrl(baseUrl) {
  return EhentaiModules.buildPathUrl(baseUrl, "popular");
};

EhentaiModules.buildWatchedUrl = function buildWatchedUrl(baseUrl) {
  return EhentaiModules.buildPathUrl(baseUrl, "watched");
};

EhentaiModules.buildGalleryPageUrl = function buildGalleryPageUrl(
  comicId,
  pageToken,
) {
  if (!EhentaiModules.hasValue(pageToken)) {
    return comicId;
  }
  return EhentaiModules.buildPathQueryUrl(comicId, "", { p: pageToken });
};

EhentaiModules.parseGalleryUrl = function parseGalleryUrl(url) {
  const clean = String(url || "")
    .split("?")[0]
    .split("#")[0];
  const segments = clean.split("/");
  return { id: segments[4], token: segments[5] };
};

EhentaiModules.buildFavoritesUrl = function buildFavoritesUrl(
  baseUrl,
  folderId,
) {
  if (!EhentaiModules.hasValue(folderId) || folderId === "-1") {
    return EhentaiModules.buildPathUrl(baseUrl, "favorites.php");
  }
  return EhentaiModules.buildPathQueryUrl(baseUrl, "favorites.php", {
    favcat: folderId,
  });
};

EhentaiModules.buildSearchUrl = function buildSearchUrl(
  baseUrl,
  keyword,
  fcats,
  stars,
) {
  const query = {
    f_search: keyword,
    f_cats: fcats ? String(fcats) : null,
    f_srdd: stars || null,
  };
  return EhentaiModules.buildPathQueryUrl(baseUrl, "", query);
};

EhentaiModules.buildToplistUrl = function buildToplistUrl(
  baseUrl,
  option,
  page,
) {
  return EhentaiModules.buildPathQueryUrl(baseUrl, "toplist.php", {
    tl: option,
    p: page,
  });
};

EhentaiModules.buildGalleryPopupUrl = function buildGalleryPopupUrl(
  baseUrl,
  galleryId,
  token,
) {
  return EhentaiModules.buildPathQueryUrl(baseUrl, "gallerypopups.php", {
    gid: galleryId,
    t: token,
    act: "addfav",
  });
};

EhentaiModules.buildArchiverUrl = function buildArchiverUrl(
  baseUrl,
  gid,
  token,
) {
  return EhentaiModules.buildPathQueryUrl(baseUrl, "archiver.php", {
    gid,
    token,
  });
};

EhentaiModules.buildCommentsUrl = function buildCommentsUrl(comicId) {
  return EhentaiModules.buildPathQueryUrl(comicId, "", { hc: 1 });
};

EhentaiModules.extractHost = function extractHost(url) {
  const regex = /^(?:https?:\/\/)?(?:www\.)?([^\/]+)/i;
  const match = String(url || "").match(regex);
  return match ? match[1] : null;
};

EhentaiModules.buildArchiveResultUrl = function buildArchiveResultUrl(
  downloadPageUrl,
  hrefPath,
) {
  const host = EhentaiModules.extractHost(downloadPageUrl);
  if (!host || !hrefPath) {
    return null;
  }
  return `${EhentaiModules.buildBaseUrl(host)}${String(hrefPath)}`;
};

EhentaiModules.normalizeGalleryLink = function normalizeGalleryLink(
  baseUrl,
  url,
) {
  const parsed = EhentaiModules.parseGalleryUrl(url);
  if (
    !EhentaiModules.hasValue(parsed.id) ||
    !EhentaiModules.hasValue(parsed.token)
  ) {
    return null;
  }
  return `${baseUrl}/g/${parsed.id}/${parsed.token}/`;
};

EhentaiModules.normalizeThumbnailHost = function normalizeThumbnailHost(url) {
  if (String(url || "").includes("s.exhentai.org")) {
    return String(url).replace("s.exhentai.org", "ehgt.org");
  }
  return url;
};

EhentaiModules.imageKeyFromPageUrl = function imageKeyFromPageUrl(url) {
  return String(url || "").split("/")[4] || "";
};

EhentaiModules.buildRateGalleryPayload = function buildRateGalleryPayload({
  galleryId,
  token,
  rating,
  apikey,
  apiuid,
}) {
  return {
    gid: galleryId,
    token,
    method: "rategallery",
    rating,
    apikey,
    apiuid,
  };
};

EhentaiModules.buildVoteCommentPayload = function buildVoteCommentPayload({
  galleryId,
  token,
  commentId,
  isUp,
  apikey,
  apiuid,
}) {
  return {
    gid: galleryId,
    token,
    method: "votecomment",
    comment_id: commentId,
    comment_vote: isUp ? 1 : -1,
    apikey,
    apiuid,
  };
};

EhentaiModules.buildImageDispatchPayload = function buildImageDispatchPayload({
  galleryId,
  imgKey,
  page,
  mpvkey,
  nl,
}) {
  return {
    gid: galleryId,
    imgkey: imgKey,
    method: "imagedispatch",
    page,
    mpvkey,
    nl,
  };
};

EhentaiModules.buildShowPagePayload = function buildShowPagePayload({
  galleryId,
  imgKey,
  page,
  showkey,
  nl,
}) {
  return {
    gid: galleryId,
    imgkey: imgKey,
    method: "showpage",
    page,
    showkey,
    nl,
  };
};

EhentaiModules.buildAddFavoriteForm = function buildAddFavoriteForm(folderId) {
  return EhentaiModules.buildFormBody({
    favcat: folderId,
    favnote: "",
    apply: "Add to Favorites",
    update: 1,
  });
};

EhentaiModules.buildDeleteFavoriteForm = function buildDeleteFavoriteForm() {
  return EhentaiModules.buildFormBody({
    favcat: "favdel",
    favnote: "",
    apply: "Apply Changes",
    update: 1,
  });
};

EhentaiModules.buildCommentForm = function buildCommentForm(content) {
  return EhentaiModules.buildFormBody({
    commenttext_new: content,
  });
};

EhentaiModules.buildArchiveDownloadForm = function buildArchiveDownloadForm(aid) {
  if (aid === "0") {
    return EhentaiModules.buildFormBody({
      dltype: "org",
      dlcheck: "Download Original Archive",
    });
  }
  if (aid === "1") {
    return EhentaiModules.buildFormBody({
      dltype: "res",
      dlcheck: "Download Resample Archive",
    });
  }
  throw new Error("Invalid archive type");
};

EhentaiModules.buildHathDownloadForm = function buildHathDownloadForm(resolution) {
  return EhentaiModules.buildFormBody({
    hathdl_xres: resolution,
  });
};

EhentaiModules.domainKey = function domainKey(url) {
  try {
    return new URL(url).hostname;
  } catch (_) {
    return "default";
  }
};

EhentaiModules.thumbnailCacheKey = function thumbnailCacheKey(comicId, pageToken) {
  return `${comicId}::${pageToken ?? "0"}`;
};

class EhentaiRequestClient {
  constructor(source) {
    this.source = source;
  }

  get(url, headers = {}, options = {}) {
    return this.send("GET", url, headers, null, options);
  }

  post(url, headers = {}, body = null, options = {}) {
    return this.send("POST", url, headers, body, options);
  }

  head(url, headers = {}, options = {}) {
    return this.send("HEAD", url, headers, null, options);
  }

  async withDocument(url, headers = {}, options = {}, parser) {
    const response = await this.get(url, headers, options);
    const document = new HtmlDocument(response.body);
    try {
      return await parser(document, response);
    } finally {
      document.dispose();
    }
  }

  async send(method, url, headers = {}, body = null, options = {}) {
    const resolved = {
      action: options.action || `${method} ${url}`,
      requestKey: options.requestKey || `${method}:${url}:${body ?? ""}`,
      domainKey: options.domainKey || EhentaiModules.domainKey(url),
      expectedStatus: options.expectedStatus ?? 200,
      maxRetries: options.maxRetries ?? (options.mutation ? 0 : 0),
      cooldownMs: options.cooldownMs ?? 60000,
      classifyBody: options.classifyBody ?? true,
      mutation: options.mutation ?? method !== "GET",
    };

    const cooldownUntil = this.source.requestState.cooldownUntil.get(
      resolved.domainKey,
    );
    if (cooldownUntil && cooldownUntil > Date.now()) {
      throw `${resolved.action} blocked: temporary cooldown in effect`;
    }

    const inflightKey = resolved.requestKey;
    if (this.source.requestState.inflight.has(inflightKey)) {
      return this.source.requestState.inflight.get(inflightKey);
    }

    const run = this._enqueueByDomain(resolved.domainKey, () =>
      this._sendWithRetry(method, url, headers, body, resolved),
    );

    this.source.requestState.inflight.set(inflightKey, run);
    try {
      return await run;
    } finally {
      this.source.requestState.inflight.delete(inflightKey);
    }
  }

  _enqueueByDomain(domainKey, task) {
    const tail = this.source.requestState.queues.get(domainKey) || Promise.resolve();
    const run = tail.then(task, task);
    const queueNext = run.then(
      () => undefined,
      () => undefined,
    );
    this.source.requestState.queues.set(domainKey, queueNext);
    queueNext.finally(() => {
      if (this.source.requestState.queues.get(domainKey) === queueNext) {
        this.source.requestState.queues.delete(domainKey);
      }
    });
    return run;
  }

  async _sendWithRetry(method, url, headers, body, options) {
    let attempt = 0;
    const maxAttempts = Math.max(0, options.maxRetries) + 1;

    while (attempt < maxAttempts) {
      attempt += 1;
      let response;
      try {
        response = await this._dispatch(method, url, headers, body);
      } catch (error) {
        if (attempt >= maxAttempts) {
          throw this.source.formatRequestError(options.action, error);
        }
        continue;
      }

      if (this._shouldCooldown(response, options)) {
        this._markCooldown(options.domainKey, options.cooldownMs);
        throw this.source.formatResponseError(options.action, response);
      }

      if (response.status !== options.expectedStatus) {
        if (attempt >= maxAttempts || options.mutation) {
          throw this.source.formatResponseError(options.action, response);
        }
        continue;
      }

      return response;
    }

    throw `${options.action} failed after retries`;
  }

  async _dispatch(method, url, headers, body) {
    if (method === "GET") {
      return Network.get(url, headers);
    }
    if (method === "POST") {
      return Network.post(url, headers, body);
    }
    return Network.sendRequest(method, url, headers, body);
  }

  _shouldCooldown(response, options) {
    if (response.status === 403 || response.status === 429) {
      return true;
    }
    if (!options.classifyBody) {
      return false;
    }
    const body = String(response.body ?? "").trim();
    if (body.length === 0) {
      return true;
    }
    return this.source.isAbuseResponseBody(body);
  }

  _markCooldown(domainKey, cooldownMs) {
    this.source.requestState.cooldownUntil.set(domainKey, Date.now() + cooldownMs);
  }
}

EhentaiModules.EhentaiRequestClient = EhentaiRequestClient;

class ImageLoadingSessionManager {
  constructor(source) {
    this.source = source;
  }

  async ensureSession(comicId) {
    const cached = this.source.imageSessionCache.get(comicId);
    if (cached) {
      return cached;
    }

    const firstPage = await this.source.comic.loadThumbnails(comicId, null);
    const key = await this.source.comic.getKey(firstPage.urls[0]);
    const session = {
      comicId,
      firstPage,
      key,
      attempts: new Map(),
    };
    this.source.imageSessionCache.set(comicId, session);
    return session;
  }

  async getPageUrl(session, page) {
    if (page < session.firstPage.urls.length) {
      return session.firstPage.urls[page];
    }

    const onePageLength = session.firstPage.thumbnails.length;
    const shouldLoadPage = Math.floor(page / onePageLength);
    const index = page % onePageLength;
    const thumbnails = await this.source.comic.loadThumbnails(
      session.comicId,
      shouldLoadPage.toString(),
    );
    return thumbnails.urls[index];
  }

  async dispatchImage({ comicId, page, nl }) {
    const session = await this.ensureSession(comicId);
    const parsed = this.source.parseUrl(comicId);

    if (session.key.mpvkey) {
      const payload = EhentaiModules.buildImageDispatchPayload({
        galleryId: parsed.id,
        imgKey: session.key.imageKeys[page],
        page: page + 1,
        mpvkey: session.key.mpvkey,
        nl,
      });
      const response = await this.source.requestClient.post(
        this.source.apiUrl,
        { "Content-Type": "application/json" },
        payload,
        {
          action: "Failed to dispatch image",
          mutation: true,
          maxRetries: 0,
          classifyBody: false,
        },
      );
      const json = JSON.parse(response.body);
      return {
        url: String(json.i),
        nl: String(json.s),
      };
    }

    const pageUrl = await this.getPageUrl(session, page);
    const payload = EhentaiModules.buildShowPagePayload({
      galleryId: parsed.id,
      imgKey: EhentaiModules.imageKeyFromPageUrl(pageUrl),
      page: page + 1,
      showkey: session.key.showkey,
      nl,
    });
    const response = await this.source.requestClient.post(
      this.source.apiUrl,
      { "Content-Type": "application/json" },
      payload,
      {
        action: "Failed to dispatch image",
        mutation: true,
        maxRetries: 0,
        classifyBody: false,
      },
    );
    const json = JSON.parse(response.body);
    const i6 = json.i6;
    const match = RegExp("nl\\('(.+?)'\\)").exec(i6);
    const nextNl = match ? match[1] : null;
    let image = json.i3;
    image = image.substring(image.indexOf('src="') + 5, image.indexOf('" style'));
    return {
      url: image,
      nl: nextNl,
    };
  }

  createRetry({ image, comicId, epId, nl, attempt }) {
    if (!nl) {
      return null;
    }

    const maxRetry = 2;
    if (attempt >= maxRetry) {
      return null;
    }

    return async () =>
      this.source.imageSessions.load({
        image,
        comicId,
        epId,
        nl,
        attempt: attempt + 1,
      });
  }

  async load({ image, comicId, epId, nl, attempt = 0 }) {
    const page = Number(image);
    const res = await this.dispatchImage({ comicId, page, nl });
    return {
      url: res.url,
      headers: {
        referer: this.source.baseUrl,
      },
      onLoadFailed: this.createRetry({
        image,
        comicId,
        epId,
        nl: res.nl,
        attempt,
      }),
    };
  }
}

EhentaiModules.ImageLoadingSessionManager = ImageLoadingSessionManager;

EhentaiModules.parsers.parseGalleryList = function parseGalleryList({
  document,
  source,
  url,
  isLeaderBoard,
}) {
  const t = isLeaderBoard ? 1 : 0;
  const galleries = [];

  for (let item of document.querySelectorAll("table.itg.gltc > tbody > tr")) {
    try {
      let time = item.children[1 + t].children[2].children[0].text;
      let stars = source.getStarsFromPosition(
        item.children[1 + t].children[2].children[1].attributes["style"],
      );
      let cover =
        item.children[1 + t].children[1].children[0].children[0].attributes[
          "src"
        ];
      if (cover[0] === "d") {
        cover =
          item.children[1 + t].children[1].children[0].children[0].attributes[
            "data-src"
          ];
      }
      let title = item.children[2 + t].children[0].children[0].text;
      let link = item.children[2 + t].children[0].attributes["href"];
      let uploader = "";
      let pages = 0;
      try {
        if (url.includes("/favorites.php")) {
          pages = Number(
            item.children[
              1 + t
            ].children[1].children[1].children[1].children[1].text.match(/\d+/)[0],
          );
        } else {
          pages = Number(item.children[3 + t].children[1].text.match(/\d+/)[0]);
          uploader = item.children[3 + t].children[0].children[0].text;
        }
      } catch (_) {}
      let tags = [];
      let language = null;
      for (let node of item.children[2 + t].children[0].children[1].children) {
        let tag = node.attributes["title"];
        if (tag.startsWith("language:")) {
          let l = tag.split(":")[1].trim();
          language = l === "translated" ? language : l;
          continue;
        }
        tags.push(tag);
      }
      galleries.push(
        new Comic({
          id: link,
          title,
          subTitle: uploader,
          cover,
          tags,
          description: time,
          stars,
          maxPage: pages,
          language,
        }),
      );
    } catch (_) {}
  }

  for (let item of document.querySelectorAll("div.gl1t")) {
    try {
      let title = item.querySelector("a")?.text ?? "Unknown";
      let time = item
        .querySelectorAll("div.gl5t > div > div")
        .find((element) => !isNaN(Date.parse(element.text)))?.text;
      let coverPath = item.querySelector("img")?.attributes["src"] ?? "";
      let stars = source.getStarsFromPosition(
        item.querySelector("div.gl5t > div > div.ir")?.attributes["style"] ?? "",
      );
      let link = item.querySelector("a")?.attributes["href"] ?? "";
      let pages = Number(
        item
          .querySelectorAll("div.gl5t > div > div")
          .find((element) => element.text.includes("page"))
          ?.text.match(/\d+/)[0] ?? "0",
      );
      galleries.push(
        new Comic({
          id: link,
          title,
          cover: coverPath,
          description: time,
          stars,
          maxPage: pages,
        }),
      );
    } catch (_) {}
  }

  for (let item of document.querySelectorAll("table.itg.glte > tbody > tr")) {
    try {
      let title = item.querySelector("td.gl2e > div > a > div > div.glink")?.text ?? "Unknown";
      let time =
        item
          .querySelectorAll("td.gl2e > div > div.gl3e > div")
          .find((element) => !isNaN(Date.parse(element.text)))?.text ?? "Unknown";
      let uploader = item.querySelector("td.gl2e > div > div.gl3e > div > a")?.text ?? "Unknown";
      let coverPath = item.querySelector("td.gl1e > div > a > img")?.attributes["src"] ?? "";
      let stars = source.getStarsFromPosition(
        item.querySelector("td.gl2e > div > div.gl3e > div.ir")?.attributes["style"] ?? "",
      );
      let link = item.querySelector("td.gl1e > div > a")?.attributes["href"] ?? "";
      let tags = item.querySelectorAll("div.gt, div.gtl").map((e) => e.attributes["title"] ?? "");
      let pages = Number(
        item
          .querySelectorAll("td.gl2e > div > div.gl3e > div")
          .find((element) => element.text.includes("page"))
          ?.text.match(/\d+/)[0] ?? "",
      );
      let language =
        tags
          .find((e) => e.startsWith("language:") && !e.includes("translated"))
          ?.split(":")[1]
          .trim() ?? null;
      galleries.push(
        new Comic({
          id: link,
          title,
          subTitle: uploader,
          cover: coverPath,
          tags,
          description: time,
          stars,
          maxPage: pages,
          language,
        }),
      );
    } catch (_) {}
  }

  for (let item of document.querySelectorAll("table.itg.gltm > tbody > tr")) {
    try {
      let title = item.querySelector("td.gl3m > a > div.glink")?.text ?? "Unknown";
      let time =
        item
          .querySelectorAll("td.gl2m > div")
          .find((element) => !isNaN(Date.parse(element.text)))?.text ?? "Unknown";
      let uploader = item.querySelector("td.gl5m > div > a")?.text ?? "Unknown";
      let coverPath = item.querySelector("td.gl2m > div > div > img")?.attributes["src"];
      if (coverPath && coverPath[0] === "d") {
        coverPath = item.querySelector("td.gl2m > div > div > img")?.attributes["data-src"];
      }
      let stars = source.getStarsFromPosition(
        item.querySelector("td.gl4m > div.ir")?.attributes["style"] ?? "",
      );
      let link = item.querySelector("td.gl3m > a")?.attributes["href"] ?? "";
      galleries.push(
        new Comic({
          id: link,
          title,
          subTitle: uploader,
          cover: coverPath,
          description: time,
          stars,
        }),
      );
    } catch (_) {}
  }

  const next = document.querySelector("a#dnext")?.attributes["href"];
  return { comics: galleries, next };
};

EhentaiModules.parsers.parseGalleryDetails = function parseGalleryDetails(document) {
  let tags = new Map();
  for (let tr of document.querySelectorAll("div#taglist > table > tbody > tr")) {
    tags.set(
      tr.children[0].text.substring(0, tr.children[0].text.length - 1),
      tr.children[1].children.map(
        (e) => e.children[0].attributes["onclick"].split(":")[1].split("'")[0],
      ),
    );
  }

  let maxPage = "1";
  for (let element of document.querySelectorAll("td.gdt2")) {
    if (element.text.includes("page")) {
      maxPage = element.text.match(/\d+/)[0];
    }
  }

  let isFavorited =
    document.querySelector("a#favoritelink")?.text !== " Add to Favorites";

  let folder = null;
  if (isFavorited) {
    let position = document
      .querySelector("div#fav")
      .children[0].attributes["style"].split("background-position:0px -")[1]
      .split("px;")[0];
    folder = (Number(position - 2) / 19).toString();
  }

  let coverPath = document.querySelector("div#gleft > div#gd1 > div").attributes["style"];
  coverPath = RegExp(
    "https?://([-a-zA-Z0-9.]+(/\\S*)?\\.(?:jpg|jpeg|gif|png|webp))",
  ).exec(coverPath)[0];

  let uploader = document.getElementById("gdn")?.children[0]?.text;
  let stars = Number(
    document.getElementById("rating_label")?.text?.split(":")?.at(1)?.trim(),
  );

  let category = document.querySelector("div.cs").text;
  tags.set("Category", [category]);
  if (uploader) {
    tags.set("uploader", [uploader]);
  }

  let time = document.querySelector("div#gdd > table > tbody > tr > td.gdt2").text;

  let script = document.querySelectorAll("script").find((e) => e.text.includes("var token"));
  let reg = RegExp("var\\s+(\\w+)\\s*=\\s*(.*?);", "g");
  let variables = new Map();
  for (let match of script?.text?.matchAll(reg) ?? []) {
    variables.set(match[1], match[2]);
  }

  let title = document.querySelector("h1#gn").text;
  let subtitle = document.querySelector("h1#gj")?.text;
  if (subtitle != null && subtitle.trim() === "") {
    subtitle = null;
  }

  return {
    title,
    subtitle,
    coverPath,
    tags,
    stars,
    maxPage: Number(maxPage),
    isFavorited,
    folder,
    time,
    token: variables.get("token"),
    apikey: variables.get("apikey"),
    uid: variables.get("apiuid"),
  };
};

EhentaiModules.parsers.parseThumbnailPage = function parseThumbnailPage(document, next) {
  const parseImageUrl = (e) => {
    let style = e.attributes["style"];
    let width = Number(style.split("width:")[1].split("px")[0]);
    let height = Number(style.split("height:")[1].split("px")[0]);
    let r = style.split("background:transparent url(")[1];
    let url = r.split(")")[0];
    let range = "";
    if (r.includes("px")) {
      let position = Number(r.split(") -")[1].split("px")[0]);
      range += `x=${position}-${position + width}`;
    }
    if (height) range += `${range ? "&" : ""}y=0-${height}`;
    if (range) url += `@${range}`;
    return url;
  };

  let images = document.querySelectorAll("div.gdtm > div").map((e) => parseImageUrl(e));
  images.push(
    ...document.querySelectorAll("div.gdtl > a > img").map((e) => e.attributes["src"]),
  );

  if (images.length === 0) {
    for (let e of document
      .querySelectorAll("div.gt100 > a > div")
      .map((e) => (e.children.length === 0 ? e : e.children[0]))) {
      images.push(parseImageUrl(e));
    }
    for (let e of document
      .querySelectorAll("div.gt200 > a > div")
      .map((e) => (e.children.length === 0 ? e : e.children[0]))) {
      images.push(parseImageUrl(e));
    }
  }

  let urls = document
    .querySelectorAll("table.ptb > tbody > tr > td > a")
    .map((e) => e.attributes["href"]);
  let pageNumbers = urls.map((e) => {
    let n = Number(e.split("=")[1]);
    return isNaN(n) ? 0 : n;
  });

  let maxPage = pageNumbers.length > 0 ? Math.max(...pageNumbers) : 0;
  let current = next ? Number(next) : 0;
  current += 1;
  let nextToken = current > maxPage ? null : current.toString();

  let imagePageUrls = document.querySelectorAll("div#gdt a").map((e) => e.attributes["href"]);

  return {
    thumbnails: images,
    urls: imagePageUrls,
    next: nextToken,
  };
};

EhentaiModules.parsers.parseDispatchKey = function parseDispatchKey(document) {
  let script = document.querySelectorAll("script").find((e) => e.text.includes("showkey"));
  if (script) {
    let reg = RegExp('showkey="(.*?)"', "g");
    let match = reg.exec(script.text);
    if (match) {
      return { showkey: match[1] };
    }
  }

  script = document.querySelectorAll("script").find((e) => e.text.includes("mpvkey"))?.text;
  if (script) {
    let mpvkey = script
      .split(";")
      .find((e) => e.includes("mpvkey"))
      .replaceAll(" ", "")
      .split("=")[1]
      .replaceAll('"', "");
    let imageList = script
      .split(";")
      .find((e) => e.includes("imagelist"))
      .replaceAll(" ", "")
      .split("=")[1];
    return {
      mpvkey,
      imageKeys: JSON.parse(imageList).map((e) => e.k),
    };
  }

  throw "Failed to get dispatch key";
};

EhentaiModules.parsers.parseComments = function parseComments(document) {
  let comments = [];
  for (let c of document.querySelectorAll("div.c1")) {
    let name = c.querySelector("div.c3 > a")?.text ?? "";
    let time =
      c
        .querySelector("div.c3")
        ?.text?.split("Posted on")
        ?.at(1)
        ?.split("by")
        ?.at(0)
        ?.trim() ?? "unknown";
    let content = "";
    if (typeof appVersion) {
      content = c.querySelector("div.c6").innerHTML;
    } else {
      content = c.querySelector("div.c6").text;
    }
    let score = Number(c.querySelector("div.c5 > span")?.text);
    if (isNaN(score)) {
      score = null;
    }
    let id = c.previousElementSibling?.attributes["name"]?.match(/\d+/)[0] ?? "0";
    let isUp =
      c.querySelector(`a#comment_vote_up_${id}`)?.attributes["style"]?.length > 0;
    let isDown =
      c.querySelector(`a#comment_vote_down_${id}`)?.attributes["style"]?.length > 0;

    comments.push(
      new Comment({
        id,
        content,
        time,
        userName: name,
        score,
        voteStatus: isUp ? 1 : isDown ? -1 : 0,
      }),
    );
  }

  return {
    comments,
    maxPage: 1,
  };
};

EhentaiModules.parsers.parseArchiveOptions = function parseArchiveOptions(document, baseUrl) {
  let body = document.querySelector("div#db");
  let index = baseUrl.includes("exhentai") ? 1 : 3;
  let archives = [];

  let hathTable = document.querySelector("table");
  if (hathTable) {
    let hathCells = hathTable.querySelectorAll("td");
    for (let cell of hathCells) {
      let link = cell.querySelector("a");
      if (link) {
        let onclick = link.attributes["onclick"];
        let resolutionMatch = onclick.match(/do_hathdl\('([^']+)'\)/);
        if (resolutionMatch) {
          let resolution = resolutionMatch[1];
          let linkText = link.text;
          let paragraphs = cell.querySelectorAll("p");
          let size = paragraphs.length > 1 ? paragraphs[1].text : "Unknown";
          let cost = paragraphs.length > 2 ? paragraphs[2].text : "Unknown";
          archives.push({
            id: `h@h_${resolution}`,
            title: `H@H ${linkText}`,
            description: `Size: ${size}, Cost: ${cost}`,
          });
        }
      }
    }
  }

  let origin = body.children[index]?.children[0];
  if (origin) {
    let originCost = origin.querySelector("div > strong")?.text || "Unknown";
    let originSize = origin.querySelector("p > strong")?.text || "Unknown";
    archives.push({
      id: "0",
      title: "Original",
      description: `Cost: ${originCost}, Size: ${originSize}`,
    });
  }

  let resample = body.children[index]?.children[1];
  if (resample) {
    let resampleCost = resample.querySelector("div > strong")?.text || "Unknown";
    let resampleSize = resample.querySelector("p > strong")?.text || "Unknown";
    archives.push({
      id: "1",
      title: "Resample",
      description: `Cost: ${resampleCost}, Size: ${resampleSize}`,
    });
  }

  return archives;
};

EhentaiModules.parsers.parseArchiveError = function parseArchiveError(document) {
  return document.querySelector("p.br")?.text || null;
};

EhentaiModules.parsers.parseFirstLink = function parseFirstLink(document) {
  return document.querySelector("a")?.attributes["href"] || null;
};

EhentaiModules.features.createAccountFeature = function createAccountFeature(source, feature) {
  return feature;
};

EhentaiModules.features.createExploreFeature = function createExploreFeature(source, feature) {
  return feature;
};

EhentaiModules.features.createSearchFeature = function createSearchFeature(source) {
  return {
    /**
     * load search result with next page token
     * @param keyword {string}
     * @param options {(string)[]} - options from optionList
     * @param next {string | null}
     * @returns {Promise<{comics: Comic[], maxPage: number}>}
     */
    loadNext: async (keyword, options, next) => {
      let category = JSON.parse(options[0]);
      let stars = options[1];
      let language = options[2];
      let fcats = 1023;
      if (!Array.isArray(category)) {
        category = [category];
      }
      for (let c of category) {
        fcats -= 1 << Number(c);
      }
      if (language && !keyword.includes("language:")) {
        keyword += ` language:${language}`;
      }
      let url = EhentaiModules.buildSearchUrl(source.baseUrl, keyword, fcats, stars);
      return source.getGalleries(next ?? url, false);
    },

    // provide options for search
    optionList: [
      {
        // type: select, multi-select, dropdown
        type: "multi-select",
        // For a single option, use `-` to separate the value and text, left for value, right for text
        options: [
          "0-Misc",
          "1-Doujinshi",
          "2-Manga",
          "3-Artist CG",
          "4-Game CG",
          "5-Image Set",
          "6-Cosplay",
          "7-Asian Porn",
          "8-Non-H",
          "9-Western",
        ],
        // option label
        label: "Category",
        // default selected options
        default: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"],
      },
      {
        // type: select, multi-select, dropdown
        // For select, there is only one selected value
        // For multi-select, there are multiple selected values or none. The `load` function will receive a json string which is an array of selected values
        // For dropdown, there is one selected value at most. If no selected value, the `load` function will receive a null
        type: "dropdown",
        // For a single option, use `-` to separate the value and text, left for value, right for text
        options: ["-<none>", "0-0", "1-1", "2-2", "3-3", "4-4", "5-5"],
        // option label
        label: "Min Stars",
      },
      {
        // type: select, multi-select, dropdown
        type: "dropdown",
        // For a single option, use `-` to separate the value and text, left for value, right for text
        options: [
          "-<none>",
          "chinese-Chinese",
          "english-English",
          "japanese-Japanese",
        ],
        // option label
        label: "Language",
      },
    ],

    // enable tags suggestions
    enableTagsSuggestions: true,
  };
};

EhentaiModules.features.createFavoritesFeature = function createFavoritesFeature(source) {
  return {
    // whether support multi folders
    multiFolder: true,
    singleFolderForSingleComic: true,
    /**
     * add or delete favorite.
     * throw `Login expired` to indicate login expired, App will automatically re-login and re-add/delete favorite
     * @param comicId {string}
     * @param folderId {string}
     * @param isAdding {boolean} - true for add, false for delete
     * @param favoriteId {string?} - [Comic.favoriteId]
     * @returns {Promise<any>} - return any value to indicate success
     */
    addOrDelFavorite: async (comicId, folderId, isAdding, favoriteId) => {
      let parsed = source.parseUrl(comicId);
      let id = parsed.id;
      let token = parsed.token;
      const url = EhentaiModules.buildGalleryPopupUrl(source.baseUrl, id, token);
      if (isAdding) {
        let res = await source.requestClient.post(
          url,
          {
            "Content-Type": "application/x-www-form-urlencoded",
          },
          EhentaiModules.buildAddFavoriteForm(folderId),
          {
            action: "Failed to add favorite",
            requestKey: `favorite:add:${comicId}:${folderId}`,
            mutation: true,
            maxRetries: 0,
          },
        );
        if (
          res.status !== 200 ||
          res.body.length === 0 ||
          res.body[0] !== "<"
        ) {
          throw "Failed to add favorite";
        }
        return "ok";
      } else {
        let res = await source.requestClient.post(
          url,
          {
            "Content-Type": "application/x-www-form-urlencoded",
          },
          EhentaiModules.buildDeleteFavoriteForm(),
          {
            action: "Failed to delete favorite",
            requestKey: `favorite:del:${comicId}`,
            mutation: true,
            maxRetries: 0,
          },
        );
        if (
          res.status !== 200 ||
          res.body.length === 0 ||
          res.body[0] !== "<"
        ) {
          throw "Failed to delete favorite";
        }
        return "ok";
      }
    },
    /**
     * load favorite folders.
     * throw `Login expired` to indicate login expired, App will automatically re-login retry.
     * if comicId is not null, return favorite folders which contains the comic.
     * @param comicId {string?}
     * @returns {Promise<{folders: {[p: string]: string}, favorited: string[]}>} - `folders` is a map of folder id to folder name, `favorited` is a list of folder id which contains the comic
     */
    loadFolders: async (comicId) => {
      try {
        await source.checkEHEvent();
      } catch (_) {}
      let res = await source.requestClient.get(
        EhentaiModules.buildFavoritesUrl(source.baseUrl, "-1"),
        {},
        {
          action: "Failed to load favorite folders",
          requestKey: "favorites:folders",
        },
      );
      if (res.status !== 200) {
        throw source.formatResponseError("Failed to load favorite folders", res);
      }
      let document = new HtmlDocument(res.body);
      let folders = new Map();
      folders.set("-1", "All");
      let sum = 0;
      for (let item of document.querySelectorAll("div.fp")) {
        if (item.text === "Show All Favorites") continue;
        let name = item.children[2]?.text ?? `Favorite ${folders.size}`;
        let length = item.children[0]?.text;
        if (length) {
          name += ` (${length})`;
          sum += +length;
        }
        folders.set((folders.size - 1).toString(), name);
      }
      folders.set("-1", `All (${sum})`);
      document.dispose();
      let favorited = [];
      if (comicId) {
        let comic = await source.comic.loadInfo(comicId);
        if (comic.isFavorite) {
          favorited.push(comic.folder);
        }
      }
      return {
        folders: folders,
        favorited: favorited,
      };
    },
    loadNext: async (next, folder) => {
      let url = EhentaiModules.buildFavoritesUrl(source.baseUrl, folder);
      return source.getGalleries(next ?? url, false);
    },
  };
};

EhentaiModules.features.createComicFeature = function createComicFeature(source) {
  return {
    /**
     * load comic info
     * @param id {string}
     * @returns {Promise<ComicDetails>}
     */
    loadInfo: async (id) => {
      if (source.galleryInfoCache.has(id)) {
        return source.galleryInfoCache.get(id);
      }
      try {
        await source.checkEHEvent();
      } catch (_) {}
      let res = await source.requestClient.get(
        id,
        {
          cookie: "nw=1",
        },
        {
          action: "Failed to load gallery details",
          requestKey: `gallery:${id}`,
        },
      );
      if (res.status !== 200) {
        throw source.formatResponseError("Failed to load gallery details", res);
      }
      if (res.body.trim().length === 0) {
        throw source.formatResponseError("Failed to load gallery details", res);
      }
      let document = new HtmlDocument(res.body);

      if (source.isLogged && source.loadSetting("hvevent")) {
        const eventPane = document.getElementById("eventpane");
        if (eventPane != null) {
          const hvUrl = eventPane.querySelector("div > a")?.attributes["href"];
          if (hvUrl != null) {
            UI.showDialog("HentaiVerse", source.translate("hentaiverse"), [
              {
                text: source.translate("cancel"),
                callback: () => {},
              },
              {
                text: source.translate("fight"),
                callback: () => {
                  UI.launchUrl(hvUrl);
                },
              },
            ]);
          }
        }
      }

      const parsed = EhentaiModules.parsers.parseGalleryDetails(document);
      let comments = source.comic.parseComments(document);

      let comic = new ComicDetails({
        id: id,
        title: parsed.title,
        subTitle: parsed.subtitle,
        cover: parsed.coverPath,
        tags: parsed.tags,
        stars: parsed.stars,
        maxPage: parsed.maxPage,
        isFavorite: parsed.isFavorited,
        // uploader: uploader,
        uploadTime: parsed.time,
        url: id,
        comments: comments.comments,
      });

      comic.folder = parsed.folder;
      comic.token = parsed.token;
      source.apikey = parsed.apikey;
      if (source.apikey && source.apikey[0] === '"') {
        source.apikey = source.apikey.substring(1, source.apikey.length - 1);
      }
      source.uid = parsed.uid;

      document.dispose();
      source.galleryInfoCache.set(id, comic);
      return comic;
    },
    /**
     * [Optional] load thumbnails of a comic
     * @param id {string}
     * @param next {string?} - next page token, null for first page
     * @returns {Promise<{thumbnails: string[], next: string?, urls: string[]}>} - `next` is next page token, null for no more
     */
    loadThumbnails: async (id, next) => {
      const cacheKey = EhentaiModules.thumbnailCacheKey(id, next);
      if (source.thumbnailCache.has(cacheKey)) {
        return source.thumbnailCache.get(cacheKey);
      }
      let url = EhentaiModules.buildGalleryPageUrl(id, next);
      let res = await source.requestClient.get(
        url,
        {
          "cache-time": "long",
          "prevent-parallel": "true",
          cookie: "nw=1",
        },
        {
          action: "Failed to load thumbnails",
          requestKey: `thumbnails:${cacheKey}`,
        },
      );
      if (res.status !== 200) {
        throw source.formatResponseError("Failed to load thumbnails", res);
      }
      let document = new HtmlDocument(res.body);
      try {
        const parsed = EhentaiModules.parsers.parseThumbnailPage(document, next);
        source.thumbnailCache.set(cacheKey, parsed);
        return parsed;
      } finally {
        document.dispose();
      }
    },

    /**
     * rate a comic
     * @param id
     * @param rating {number} - [0-10] app use 5 stars, 1 rating = 0.5 stars,
     * @returns {Promise<any>}
     */
    starRating: async (id, rating) => {
      const parsed = source.parseUrl(id);
      let res = await source.requestClient.post(
        source.apiUrl,
        {
          "Content-Type": "application/json",
        },
        EhentaiModules.buildRateGalleryPayload({
          galleryId: parsed.id,
          token: parsed.token,
          rating: rating,
          apikey: source.apikey,
          apiuid: source.uid,
        }),
        {
          action: "Failed to submit rating",
          requestKey: `rate:${id}:${rating}`,
          mutation: true,
          maxRetries: 0,
          classifyBody: false,
        },
      );
      if (res.status !== 200) {
        throw source.formatResponseError("Failed to submit rating", res);
      }
      return "ok";
    },

    getKey: async (url) => {
      if (source.keyCache.has(url)) {
        return source.keyCache.get(url);
      }
      let res = await source.requestClient.get(
        url,
        {
          "cache-time": "long",
          "prevent-parallel": "true",
        },
        {
          action: "Failed to load dispatch key",
          requestKey: `key:${url}`,
        },
      );
      if (res.status !== 200) {
        throw source.formatResponseError("Failed to load dispatch key", res);
      }
      let document = new HtmlDocument(res.body);
      try {
        const parsed = EhentaiModules.parsers.parseDispatchKey(document);
        source.keyCache.set(url, parsed);
        return parsed;
      } finally {
        document.dispose();
      }
    },
    /**
     * load images of a chapter
     * @param comicId {string}
     * @param epId {string?}
     * @returns {Promise<{images: string[]}>}
     */
    loadEp: async (comicId, epId) => {
      let comic = await source.comic.loadInfo(comicId);
      return {
        images: Array.from({ length: comic.maxPage }, (_, i) => i.toString()),
      };
    },
    /**
     * [Optional] provide configs for an image loading
     * @param image
     * @param comicId
     * @param epId
     * @param nl
     * @returns {{}}
     */
    onImageLoad: async (image, comicId, epId, nl) => {
      return source.imageSessions.load({ image, comicId, epId, nl, attempt: 0 });
    },
    /**
     * [Optional] provide configs for a thumbnail loading
     * @param url {string}
     * @returns {{}}
     */
    onThumbnailLoad: (url) => {
      url = EhentaiModules.normalizeThumbnailHost(url);
      return {
        url: url,
        headers: {
          referer: source.baseUrl,
        },
      };
    },
    parseComments: (document) => {
      return EhentaiModules.parsers.parseComments(document);
    },
    /**
     * [Optional] load comments
     * @param comicId {string}
     * @param subId {string?} - ComicDetails.subId
     * @param page {number}
     * @param replyTo {string?} - commentId to reply, not null when reply to a comment
     * @returns {Promise<{comments: Comment[], maxPage: number?}>}
     */
    loadComments: async (comicId, subId, page, replyTo) => {
      let res = await source.requestClient.get(
        EhentaiModules.buildCommentsUrl(comicId),
        {
          cookie: "nw=1",
        },
        {
          action: "Failed to load comments",
          requestKey: `comments:${comicId}`,
        },
      );
      if (res.status !== 200) {
        throw source.formatResponseError("Failed to load comments", res);
      }
      let document = new HtmlDocument(res.body);
      let result = source.comic.parseComments(document);
      document.dispose();
      return result;
    },
    /**
     * [Optional] send a comment, return any value to indicate success
     * @param comicId {string}
     * @param subId {string?} - ComicDetails.subId
     * @param content {string}
     * @param replyTo {string?} - commentId to reply, not null when reply to a comment
     * @returns {Promise<any>}
     */
    sendComment: async (comicId, subId, content, replyTo) => {
      let res = await source.requestClient.post(
        comicId,
        {
          "Content-Type": "application/x-www-form-urlencoded",
          referer: comicId,
        },
        EhentaiModules.buildCommentForm(content),
        {
          action: "Failed to submit comment",
          requestKey: `comment:${comicId}`,
          mutation: true,
          maxRetries: 0,
        },
      );
      if (res.status >= 400) {
        throw source.formatResponseError("Failed to submit comment", res);
      }
      let document = new HtmlDocument(res.body);
      if (document.querySelector("p.br")) {
        throw document.querySelector("p.br").text;
      }
      return "ok";
    },
    /**
     * [Optional] vote a comment
     * @param id {string} - comicId
     * @param subId {string?} - ComicDetails.subId
     * @param commentId {string} - commentId
     * @param isUp {boolean} - true for up, false for down
     * @param isCancel {boolean} - true for cancel, false for vote
     * @returns {Promise<number>} - new score
     */
    voteComment: async (id, subId, commentId, isUp, isCancel) => {
      if (source.apikey == null || source.uid == null) {
        throw "Login required";
      }

      const parsed = source.parseUrl(id);
      let res = await source.requestClient.post(
        source.apiUrl,
        {
          "Content-Type": "application/json",
        },
        EhentaiModules.buildVoteCommentPayload({
          galleryId: parsed.id,
          token: parsed.token,
          commentId,
          isUp,
          apikey: source.apikey,
          apiuid: source.uid,
        }),
        {
          action: "Failed to vote comment",
          requestKey: `vote:${id}:${commentId}:${isUp ? "up" : "down"}`,
          mutation: true,
          maxRetries: 0,
          classifyBody: false,
        },
      );

      let json = JSON.parse(res.body);

      if (json.error) {
        throw json.error;
      }

      return json.comment_score;
    },
    archive: {
      getArchives: async (cid) => {
        let comicInfo = await source.comic.loadInfo(cid);
        let urlParseResult = source.parseUrl(cid);
        let gid = urlParseResult.id;
        let token = urlParseResult.token;
        const archiveUrl = EhentaiModules.buildArchiverUrl(source.baseUrl, gid, token);
        let res = await source.requestClient.get(
          archiveUrl,
          {},
          {
            action: "Failed to load archive options",
            requestKey: `archive:options:${cid}`,
          },
        );
        if (res.status !== 200) {
          throw source.formatResponseError("Failed to load archive options", res);
        }
        let document = new HtmlDocument(res.body);
        try {
          return EhentaiModules.parsers.parseArchiveOptions(document, source.baseUrl);
        } finally {
          document.dispose();
        }
      },
      getDownloadUrl: async (cid, aid) => {
        let urlParseResult = source.parseUrl(cid);
        let gid = urlParseResult.id;
        let token = urlParseResult.token;
        const archiveUrl = EhentaiModules.buildArchiverUrl(source.baseUrl, gid, token);

        // Handle H@H Download options
        if (aid.startsWith("h@h_")) {
          let resolution = aid.substring(4); // Remove 'h@h_' prefix

          // For H@H downloads, send the command directly to archiver.php
          let hathRes = await source.requestClient.post(
            archiveUrl,
            {
              "Content-Type": "application/x-www-form-urlencoded",
            },
            EhentaiModules.buildHathDownloadForm(resolution),
            {
              action: "Failed to send H@H download command",
              requestKey: `archive:hath:${cid}:${resolution}`,
              mutation: true,
              maxRetries: 0,
            },
          );

          if (hathRes.status !== 200) {
            throw source.formatResponseError(
              "Failed to send H@H download command",
              hathRes,
            );
          }

          // Parse response for any error messages
          let hathDocument = new HtmlDocument(hathRes.body);
          let errorElement = hathDocument.querySelector("p.br");

          if (errorElement) {
            let errorMessage = errorElement.text;
            hathDocument.dispose();

            if (errorMessage.includes("H@H client")) {
              throw "You need an H@H client associated with your account to use this feature";
            } else if (errorMessage.includes("offline")) {
              throw "Your H@H client appears to be offline. Please start it and try again";
            } else if (errorMessage.includes("resolution")) {
              throw "This gallery cannot be downloaded at the selected resolution";
            } else {
              throw errorMessage;
            }
          }

          // Check for success message or assume success if no error
          let successMessage = hathDocument.querySelector("p")?.text;
          hathDocument.dispose();

          let resolutionText =
            resolution === "org"
              ? "Original"
              : resolution === "800"
                ? "800x"
                : resolution === "1280"
                  ? "1280x"
                  : resolution === "1920"
                    ? "1920x"
                    : resolution === "2560"
                      ? "2560x"
                      : resolution;

          // For H@H downloads, return a special value to indicate remote download
          // This should close the window without creating a local download task
          // let message = successMessage && successMessage.includes("successfully")
          //     ? `H@H download command sent successfully (${resolutionText}). Check your H@H client.`
          //     : `H@H download command sent (${resolutionText}). Check your H@H client.`;

          // // Show success message to user
          // UI.showMessage(message);

          // Return empty string to avoid type error and prevent download task creation
          return "";
        }

        // Handle regular downloads (Original and Resample)
        let res = await source.requestClient.post(
          archiveUrl,
          {
            "Content-Type": "application/x-www-form-urlencoded",
          },
          EhentaiModules.buildArchiveDownloadForm(aid),
          {
            action: "Failed to create archive download",
            requestKey: `archive:create:${cid}:${aid}`,
            mutation: true,
            maxRetries: 0,
          },
        );
        if (res.status !== 200) {
          throw source.formatResponseError(
            "Failed to create archive download",
            res,
          );
        }
        let document = new HtmlDocument(res.body);
        let link = document.querySelector("a")?.attributes["href"];
        if (!link) {
          throw "Failed to get download link";
        }
        let res2 = await source.requestClient.get(
          link,
          {
            http_client: "dart:io", // The server is uncomfortable with the default client
          },
          {
            action: "Failed to load archive download page",
            requestKey: `archive:page:${link}`,
          },
        );
        document.dispose();
        document = new HtmlDocument(res2.body);
        let link2 = document.querySelector("a")?.attributes["href"];
        document.dispose();
        let resultLink = EhentaiModules.buildArchiveResultUrl(link, link2);
        if (!resultLink) {
          throw "Failed to build final download URL";
        }
        let test = await source.requestClient.head(
          resultLink,
          {
            http_client: "dart:io",
          },
          {
            action: "Failed to validate archive link",
            requestKey: `archive:head:${resultLink}`,
            classifyBody: false,
          },
        );
        if (test.status === 410) {
          throw "IP quota exhausted.";
        }
        return resultLink;
      },
    },
    /**
     * [Optional] Handle tag click event
     * @param namespace {string}
     * @param tag {string}
     * @returns {{action: string, keyword: string, param: string?}}
     */
    onClickTag: (namespace, tag) => {
      if (namespace == "Category") {
        const categories = [
          "misc",
          "doujinshi",
          "manga",
          "artist cg",
          "game cg",
          "image set",
          "cosplay",
          "asian porn",
          "non-h",
          "western",
        ];
        return {
          page: "search",
          attributes: {
            keyword: "",
            options: [categories.indexOf(tag.toLowerCase()).toString(), "", ""],
          },
        };
      }
      if (tag.includes(" ")) {
        tag = `"${tag}"`;
      }
      return {
        // 'search' or 'category'
        action: "search",
        keyword: `${namespace}:${tag}`,
        // {string?} only for category action
        param: null,
      };
    },
    /**
     * [Optional] Handle links
     */
    link: {
      /**
       * set accepted domains
       */
      domains: ["e-hentai.org", "exhentai.org"],
      /**
       * parse url to comic id
       * @param url {string}
       * @returns {string | null}
       */
      linkToId: (url) => {
        return EhentaiModules.normalizeGalleryLink(source.baseUrl, url);
      },
    },
    enableTagsTranslate: true,
  };
};

EhentaiModules.features.createCommentsFeature = function createCommentsFeature(source, feature) {
  return feature;
};

EhentaiModules.features.createArchiveFeature = function createArchiveFeature(source, feature) {
  return feature;
};

EhentaiModules.settings = {
  domain: {
    title: "domain",
    type: "select",
    options: [
      {
        value: "e-hentai.org",
      },
      {
        value: "exhentai.org",
      },
    ],
    default: "e-hentai.org",
  },
  ehevent: {
    title: "ehevent",
    type: "switch",
    default: false,
  },
  hvevent: {
    title: "hvevent",
    type: "switch",
    default: false,
  },
};

EhentaiModules.i18n = {
  zh_CN: {
    domain: "域名",
    ehevent: "触发黎明事件",
    hvevent: "提示HV遭遇战",
    hentaiverse: "你遇到了怪物！",
    fight: "战斗",
    cancel: "取消",
    language: "语言",
    artist: "画师",
    male: "男性",
    female: "女性",
    mixed: "混合",
    other: "其它",
    parody: "原作",
    character: "角色",
    group: "团队",
    cosplayer: "Coser",
    reclass: "重新分类",
    uploader: "上传者",
    Languages: "语言",
    Artists: "画师",
    Characters: "角色",
    Groups: "团队",
    Tags: "标签",
    Parodies: "原作",
    Categories: "分类",
    Category: "分类",
    "Min Stars": "最少星星",
    Language: "语言",
    "H@H Original": "H@H 原版",
    "H@H 800x": "H@H 800x",
    "H@H 1280x": "H@H 1280x",
    "H@H 1920x": "H@H 1920x",
    "H@H 2560x": "H@H 2560x",
    Original: "原版",
    Resample: "重采样",
  },
  zh_TW: {
    domain: "域名",
    ehevent: "觸發黎明事件",
    hvevent: "提示HV遭遇戰",
    hentaiverse: "你遇到了怪物！",
    fight: "戰鬥",
    cancel: "取消",
    language: "語言",
    artist: "畫師",
    male: "男性",
    female: "女性",
    mixed: "混合",
    other: "其他",
    parody: "原作",
    character: "角色",
    group: "團隊",
    cosplayer: "Coser",
    reclass: "重新分類",
    uploader: "上傳者",
    Languages: "語言",
    Artists: "畫師",
    Characters: "角色",
    Groups: "團隊",
    Tags: "標籤",
    Parodies: "原作",
    Categories: "分類",
    Category: "分類",
    "Min Stars": "最少星星",
    Language: "語言",
    "H@H Original": "H@H 原版",
    "H@H 800x": "H@H 800x",
    "H@H 1280x": "H@H 1280x",
    "H@H 1920x": "H@H 1920x",
    "H@H 2560x": "H@H 2560x",
    Original: "原版",
    Resample: "重採樣",
  },
  en_US: {
    domain: "Domain",
    ehevent: "Trigger Dawn Event",
    hvevent: "HV Encounter Alert",
    hentaiverse: "You have encountered a monster!",
    fight: "Fight",
    cancel: "Cancel",
    language: "Language",
    artist: "Artist",
    male: "Male",
    female: "Female",
    mixed: "Mixed",
    other: "Other",
    parody: "Parody",
    character: "Character",
    group: "Group",
    cosplayer: "Cosplayer",
    reclass: "Reclass",
    uploader: "Uploader",
    Languages: "Languages",
    Artists: "Artists",
    Characters: "Characters",
    Groups: "Groups",
    Tags: "Tags",
    Parodies: "Parodies",
    Categories: "Categories",
    Category: "Category",
    "Min Stars": "Min Stars",
    Language: "Language",
    "H@H Original": "H@H Original",
    "H@H 800x": "H@H 800x",
    "H@H 1280x": "H@H 1280x",
    "H@H 1920x": "H@H 1920x",
    "H@H 2560x": "H@H 2560x",
    Original: "Original",
    Resample: "Resample",
  },
};

class Ehentai extends ComicSource {
  // Note: The fields which are marked as [Optional] should be removed if not used

  // name of the source
  name = "ehentai";

  // unique id of the source
  key = "ehentai";

  version = "1.2.0";

  minAppVersion = "1.5.3";

  // update url
  url = EhentaiModules.buildCdnSourceUrl("ehentai.js");

  /**
   * cached api key
   * @type {string | null}
   */
  apiKey = null;

  /**
   * cached uid key
   * @type {string | null}
   */
  uid = null;

  requestState = {
    queues: new Map(),
    inflight: new Map(),
    cooldownUntil: new Map(),
    failureBudget: new Map(),
  };

  // In-memory caches only. Never persist session-derived runtime data.
  responseCache = new Map();
  thumbnailCache = new Map();
  keyCache = new Map();
  galleryInfoCache = new Map();
  imageSessionCache = new Map();

  /**
   * @param url
   * @returns {{id: string, token: string}}
   */
  parseUrl(url) {
    return EhentaiModules.parseGalleryUrl(url);
  }

  get requestClient() {
    if (!this._requestClient) {
      this._requestClient = new EhentaiModules.EhentaiRequestClient(this);
    }
    return this._requestClient;
  }

  get imageSessions() {
    if (!this._imageSessions) {
      this._imageSessions = new EhentaiModules.ImageLoadingSessionManager(this);
    }
    return this._imageSessions;
  }

  getErrorMessage(error) {
    if (error == null) {
      return "Unknown error";
    }
    if (typeof error === "string") {
      return error;
    }
    if (error instanceof Error && error.message) {
      return error.message;
    }
    if (typeof error.message === "string" && error.message.length > 0) {
      return error.message;
    }
    return String(error);
  }

  isRedirectError(error) {
    return this.getErrorMessage(error).toLowerCase().includes("redirect");
  }

  isAbuseResponseBody(body) {
    let text = String(body ?? "").trim();
    if (text.length === 0) {
      return true;
    }
    let lower = text.toLowerCase();
    return (
      lower.includes("your ip address has been banned") ||
      lower.includes("access denied") ||
      lower.includes("request denied") ||
      lower.includes("temporarily banned")
    );
  }

  formatRequestError(action, error) {
    let message = this.getErrorMessage(error);
    if (this.isRedirectError(message)) {
      return `${action} failed: request was redirected by the server`;
    }
    if (
      message.toLowerCase().includes("timeout") ||
      message.toLowerCase().includes("network") ||
      message.toLowerCase().includes("socket")
    ) {
      return `${action} failed: network error (${message})`;
    }
    return `${action} failed: ${message}`;
  }

  formatResponseError(action, response) {
    let status = response?.status;
    let body = String(response?.body ?? "").trim();
    if (status === 403 || status === 429) {
      return `${action} failed: server returned ${status}`;
    }
    if (body.length === 0) {
      return `${action} failed: empty response from server`;
    }
    if (this.isAbuseResponseBody(body)) {
      return `${action} failed: access was denied by the server`;
    }
    return `${action} failed: invalid status code ${status}`;
  }

  async checkEHEvent() {
    if (!this.isLogged) {
      return;
    }
    if (!this.loadSetting("ehevent")) {
      return;
    }
    try {
      const lastEvent = this.loadData("lastEventTime");
      const newTime = new Date().toISOString().split("T")[0];
      if (lastEvent == newTime) {
        return;
      }
      const res = await this.requestClient.get(EhentaiModules.buildEhNewsUrl(), {}, {
        action: "Failed to load event news",
        requestKey: "event-news",
      });
      if (res.status !== 200 || this.isAbuseResponseBody(res.body)) {
        return;
      }
      this.saveData("lastEventTime", newTime);
      const document = new HtmlDocument(res.body);
      const eventPane = document.getElementById("eventpane");
      if (eventPane == null) {
        return;
      }
      const dawnInfo = eventPane.querySelector("div > p:nth-child(2)");
      if (dawnInfo == null) {
        return;
      }
      UI.showMessage(dawnInfo.text);
    } catch (error) {
      // Event checks are advisory; never let them break the main request path.
    }
  }

  // [Optional] account related
  account = EhentaiModules.features.createAccountFeature(this, {
    /**
     * [Optional] login with webview
     */
    loginWithWebview: {
      url: EhentaiModules.buildForumsLoginUrl(),
      /**
       * check login status
       * @param url {string} - current url
       * @param title {string} - current title
       * @returns {boolean} - return true if login success
       */
      checkStatus: (url, title) => {
        return title === "E-Hentai Forums";
      },
      onLoginSuccess: async () => {
        let cookies = await Network.getCookies(EhentaiModules.buildForumsCookieUrl());
        cookies.forEach((cookie) => {
          cookie.domain = ".exhentai.org";
        });
        Network.setCookies(EhentaiModules.buildExCookieUrl(), cookies);
      },
    },

    loginWithCookies: {
      fields: ["ipb_member_id", "ipb_pass_hash", "igneous", "star"],
      /**
       * Validate cookies, return false if cookies are invalid.
       *
       * Use `Network.setCookies` to set cookies before validate.
       * @param values {string[]} - same order as `fields`
       * @returns {Promise<boolean>}
       */
      validate: async (values) => {
        if (values.length !== 4) {
          return false;
        }
        if (values[0].length === 0 || values[1].length === 0) {
          return false;
        }
        let cookies = [];
        for (let i = 0; i < values.length; i++) {
          cookies.push(
            new Cookie({
              name: this.account.loginWithCookies.fields[i],
              value: values[i],
              domain: ".e-hentai.org",
            }),
          );
          cookies.push(
            new Cookie({
              name: this.account.loginWithCookies.fields[i],
              value: values[i],
              domain: ".exhentai.org",
            }),
          );
        }
        Network.deleteCookies(EhentaiModules.buildEhCookieUrl());
        Network.setCookies(EhentaiModules.buildEhCookieUrl(), cookies);
        let res = await Network.get(EhentaiModules.buildForumsHomeUrl(), {
          referer: EhentaiModules.buildForumsIndexRefererUrl(),
          accept:
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
          "accept-encoding": "gzip, deflate, br",
          "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        });
        if (res.status !== 200) {
          return false;
        }
        let document = new HtmlDocument(res.body);
        let name = document.querySelector("div#userlinks > p.home > b > a");
        document.dispose();
        return name != null;
      },
    },

    /**
     * logout function, clear account related data
     */
    logout: () => {
      Network.deleteCookies(EhentaiModules.buildEhCookieUrl());
      Network.deleteCookies(EhentaiModules.buildForumsCookieUrl());
      Network.deleteCookies(EhentaiModules.buildExCookieUrl());
      this.responseCache.clear();
      this.thumbnailCache.clear();
      this.keyCache.clear();
      this.galleryInfoCache.clear();
      this.imageSessionCache.clear();
    },

    // {string?} - register url
    registerWebsite: null,
  });

  get baseUrl() {
    return EhentaiModules.buildBaseUrl(this.loadSetting("domain"));
  }

  get apiUrl() {
    return EhentaiModules.buildApiUrl(this.baseUrl);
  }

  getStarsFromPosition(position) {
    let i = 0;
    while (position[i] !== ";") {
      i++;
      if (i === position.length) {
        break;
      }
    }
    switch (position.substring(0, i)) {
      case "background-position:0px -1px":
        return 5;
      case "background-position:0px -21px":
        return 4.5;
      case "background-position:-16px -1px":
        return 4;
      case "background-position:-16px -21px":
        return 3.5;
      case "background-position:-32px -1px":
        return 3;
      case "background-position:-32px -21px":
        return 2.5;
      case "background-position:-48px -1px":
        return 2;
      case "background-position:-48px -21px":
        return 1.5;
      case "background-position:-64px -1px":
        return 1;
      case "background-position:-64px -21px":
        return 0.5;
    }
    return 0.5;
  }

  async onLoadFailed(reason = null) {
    let cookies;
    try {
      cookies = await Network.getCookies(EhentaiModules.buildEhCookieUrl());
    } catch (error) {
      throw this.formatRequestError("Failed to recover session cookies", error);
    }
    cookies.forEach((c) => {
      c.domain = ".exhentai.org";
    });
    cookies = cookies.filter((item) => item.name !== "igneous");
    Network.deleteCookies(EhentaiModules.buildExCookieUrl());
    Network.setCookies(EhentaiModules.buildExCookieUrl(), cookies);
    let suffix = reason ? ` (${reason})` : "";
    throw `You may not have permission to access this page${suffix}. Please check your network or try to login again.`;
  }

  /**
   *
   * @param url {string}
   * @param isLeaderBoard {boolean}
   * @returns {Promise<{comics: Comic[], next: string?}>}
   */
  async getGalleries(url, isLeaderBoard) {
    try {
      await this.checkEHEvent();
    } catch (_) {}
    let t = isLeaderBoard ? 1 : 0;
    let res;
    try {
      res = await this.requestClient.get(url, {}, {
        action: "Failed to load gallery list",
        requestKey: `galleries:${url}`,
      });
    } catch (e) {
      if (this.isRedirectError(e)) {
        await this.onLoadFailed("request was redirected");
      }
      throw this.formatRequestError("Failed to load gallery list", e);
    }
    if (res.status !== 200) {
      throw this.formatResponseError("Failed to load gallery list", res);
    }
    if (res.body.trim().length === 0) {
      await this.onLoadFailed("empty response from gallery list");
    }
    if (res.body[0] !== "<") {
      if (this.isAbuseResponseBody(res.body)) {
        throw "Your IP address has been banned";
      }
      throw "Failed to load gallery list";
    }
    let document = new HtmlDocument(res.body);
    try {
      return EhentaiModules.parsers.parseGalleryList({
        document,
        source: this,
        url,
        isLeaderBoard,
      });
    } finally {
      document.dispose();
    }
  }

  // explore page list
  explore = EhentaiModules.features.createExploreFeature(this, [
    {
      // title of the page.
      // title is used to identify the page, it should be unique
      title: "eh latest",

      /// multiPartPage or multiPageComicList or mixed
      type: "multiPageComicList",

      loadNext: (next) => {
        return this.getGalleries(next ?? this.baseUrl, false);
      },
    },
    {
      // title of the page.
      // title is used to identify the page, it should be unique
      title: "eh popular",

      /// multiPartPage or multiPageComicList or mixed
      type: "multiPageComicList",

      loadNext: (next) => {
        return this.getGalleries(
          next ?? EhentaiModules.buildPopularUrl(this.baseUrl),
          false,
        );
      },
    },
    {
      // title of the page.
      // title is used to identify the page, it should be unique
      title: "eh watched",

      /// multiPartPage or multiPageComicList or mixed
      type: "multiPageComicList",

      loadNext: async (next) => {
        if (!this.isLogged) {
          UI.showMessage("Need login first");
          return {
            comics: [],
            next: null,
          };
        }
        return this.getGalleries(
          next ?? EhentaiModules.buildWatchedUrl(this.baseUrl),
          false,
        );
      },
    },
  ]);

  // categories
  category = {
    /// title of the category page, used to identify the page, it should be unique
    title: "ehentai",
    parts: [],
    // enable ranking page
    enableRankingPage: true,
  };

  /// category comic loading related
  categoryComics = {
    ranking: {
      // For a single option, use `-` to separate the value and text, left for value, right for text
      options: ["15-yesterday", "13-month", "12-year", "11-all"],
      /**
       * load ranking comics
       * @param option {string} - option from optionList
       * @param page {number} - page number
       * @returns {Promise<{comics: Comic[], maxPage: number}>}
       */
      load: async (option, page) => {
        let res = await this.getGalleries(
          EhentaiModules.buildToplistUrl(
            EhentaiModules.buildBaseUrl("e-hentai.org"),
            option,
            page - 1,
          ),
          true,
        );
        let comics = res.comics;
        if (this.loadSetting("domain") === "exhentai.org") {
          comics.forEach((e) => {
            e.id = e.id.replace("e-hentai", "exhentai");
          });
        }
        return {
          comics: comics,
          maxPage: 200,
        };
      },
    },
  };

  /// search related
  search = EhentaiModules.features.createSearchFeature(this);

  // favorite related
  favorites = EhentaiModules.features.createFavoritesFeature(this);

  /// single comic related
  comic = EhentaiModules.features.createComicFeature(this);

  /*
    [Optional] settings related
    Use this.loadSetting to load setting
    ```
    let setting1Value = this.loadSetting('setting1')
    console.log(setting1Value)
    ```
     */
  settings = EhentaiModules.settings;

  // [Optional] translations for the strings in this config
  translation = EhentaiModules.i18n;
}
