#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const sourceName = process.argv[2];

if (sourceName !== "ehentai") {
  throw new Error("Usage: node scripts/build-source.js ehentai");
}

const moduleOrder = [
  "src/ehentai/index.js",
  "src/ehentai/query.js",
  "src/ehentai/urls.js",
  "src/ehentai/api-payloads.js",
  "src/ehentai/form-payloads.js",
  "src/ehentai/cache-keys.js",
  "src/ehentai/request-client.js",
  "src/ehentai/image-session.js",
  "src/ehentai/parsers/gallery-list-parser.js",
  "src/ehentai/parsers/gallery-detail-parser.js",
  "src/ehentai/parsers/thumbnail-parser.js",
  "src/ehentai/parsers/dispatch-key-parser.js",
  "src/ehentai/parsers/comment-parser.js",
  "src/ehentai/parsers/archive-parser.js",
  "src/ehentai/features/account.js",
  "src/ehentai/features/explore.js",
  "src/ehentai/features/search.js",
  "src/ehentai/features/favorites.js",
  "src/ehentai/features/comic.js",
  "src/ehentai/features/comments.js",
  "src/ehentai/features/archive.js",
  "src/ehentai/settings.js",
  "src/ehentai/i18n.js",
  "src/ehentai/source-shell.js",
];

const outputPath = path.join(repoRoot, "ehentai.js");
const banner = [
  "// Generated from src/ehentai. Do not edit this file directly.",
  "// Run: node scripts/build-source.js ehentai",
  "",
].join("\n");

const parts = moduleOrder.map((relativePath) => {
  const fullPath = path.join(repoRoot, relativePath);
  if (!fs.existsSync(fullPath)) {
    throw new Error(`Missing module: ${relativePath}`);
  }
  return fs.readFileSync(fullPath, "utf8").trimEnd();
});

const output = `${banner}${parts.join("\n\n")}\n`;
fs.writeFileSync(outputPath, output, "utf8");
console.log("Built ehentai.js from src/ehentai");
